<?php
$value = array (
  'youtube' => 'testeyoutube',
  'facebook' => 'testefacebook',
  'orkut' => 'testeintagram',
  'box-facebook' => 'http://www.facebook.com/VipcomColetiva',
  'usuario_twitter' => 'VipcomColetivas',
  'id_twitter' => '',
  'admin_id_login' => '',
  'app_id_login' => '',
  'colormenusuperior' => '#094281',
  'colormenusuperiorhover' => '#094281',
  'colormenusuperiorborder' => '#224774',
  'colortitulocidade' => '#0f0f0f',
  'colorfundocidades' => '#336105',
  'color_fundo_laterais_rodape' => '#f1f6f9',
  'color_fundo_meio_rodape' => '#03254B',
  'background_titulo_destaque' => '#303030',
  'botaodetalhe' => '#222222',
  'botaodetalhehover' => '#303030',
  'background_titulos' => '#F1F1F1',
  'background_oferta_nacional' => '#B33191',
  'cor_letra_topo' => '#fff',
  'rodape_cor_fundo' => '',
  'cor_bloco_artigo' => '',
  'cor_bloco_form' => '',
  'bloco_artigo_texto' => '',
);
?>